language: objective-c
osx_image: xcode6.3
xcode_project: SmartDeviceLink-iOS/SmartDeviceLink-iOS.xcodeproj
xcode_scheme: SmartDeviceLink
xcode_sdk: iphonesimulator8.1

notifications:
  email: false

before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool