language: objective-c
osx_image: xcode6.4

notifications:
  email: false

before_script:
  - brew update
  - brew install xctool
  - brew outdated xctool || brew upgrade xctool

script:
  - xctool test -project SmartDeviceLink-iOS/SmartDeviceLink-iOS.xcodeproj -scheme SmartDeviceLink -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO RUN_CLANG_STATIC_ANALYZER=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES

after_script:
  - bash <(curl -s https://codecov.io/bash)